# Generated by Django 2.0.9 on 2019-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
