# Generated by Django 2.0.9 on 2019-03-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='tour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tour_registrations', to='tour.Tour'),
            preserve_default=False,
        ),
    ]
