# Generated by Django 2.0.9 on 2019-04-03 13:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20190403_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='national_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passport_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
