# Generated by Django 2.1.7 on 2019-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_ticket_is_persian'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='is_persian',
            field=models.BooleanField(default=True),
        ),
    ]
