# Generated by Django 2.1.7 on 2019-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tourregistration_is_persian'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
