# Generated by Django 2.1.7 on 2019-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tourregistration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
