# Generated by Django 2.1.7 on 2019-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passport_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
