# Generated by Django 2.1.7 on 2019-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_auto_20190401_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start',
            field=models.DateField(),
        ),
    ]
