# Generated by Django 2.1.7 on 2019-04-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_tourregistration_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
