# Generated by Django 2.1.7 on 2019-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_tourregistration_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
