# Generated by Django 2.1.7 on 2019-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20190403_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nationality',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
