# Generated by Django 2.1.7 on 2019-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_auto_20190404_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nationality',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
    ]
