# Generated by Django 2.1.7 on 2019-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20190404_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
