# Generated by Django 2.1.7 on 2019-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_auto_20190407_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
