# Generated by Django 2.1.7 on 2019-04-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_auto_20190407_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.TextField(),
        ),
    ]
