# Generated by Django 2.1.7 on 2019-04-15 07:53

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_auto_20190409_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
