# Generated by Django 2.1.7 on 2019-04-15 08:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20190415_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
