# Generated by Django 2.1.7 on 2019-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_tourregistration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
