# Generated by Django 2.1.7 on 2019-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_tourregistration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourregistration',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
