# Generated by Django 2.1.7 on 2019-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_auto_20190416_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
