# Generated by Django 2.1.7 on 2019-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_auto_20190421_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
