# Generated by Django 2.1.7 on 2019-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0024_auto_20190422_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
