# Generated by Django 2.1.7 on 2019-05-10 16:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0025_auto_20190422_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
