# Generated by Django 2.1.7 on 2019-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0026_auto_20190510_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
