# Generated by Django 2.1.7 on 2019-05-10 16:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_auto_20190510_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
