# Generated by Django 2.1.7 on 2019-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0028_auto_20190510_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
