# Generated by Django 2.1.7 on 2019-05-13 06:17

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0029_auto_20190512_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2019, 5, 13, 6, 17, 7, 103543, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
