# Generated by Django 2.1.7 on 2019-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0030_auto_20190513_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='date_registered',
        ),
        migrations.AlterField(
            model_name='tour',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourregistration',
            name='date',
            field=models.DateField(),
        ),
    ]
