# Generated by Django 2.1.7 on 2019-05-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190313_1154'),
        ('tour', '0031_auto_20190521_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=255)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('is_persian', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('verified_price', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
