# Generated by Django 2.1.7 on 2019-05-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0032_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tour_reg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='tour.TourRegistration'),
        ),
        migrations.AlterField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='users.UserProfile'),
        ),
    ]
