# Generated by Django 2.1.7 on 2019-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0033_auto_20190523_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='verified_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourregistration',
            name='verified_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
