# Generated by Django 2.1.7 on 2019-05-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0034_auto_20190523_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='log',
            name='tour_reg',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
