# Generated by Django 2.1.7 on 2019-05-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0035_auto_20190523_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourregistration',
            name='verified_price',
        ),
        migrations.AddField(
            model_name='tourregistration',
            name='tour_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourregistration',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_registrations', to='tour.Tour'),
        ),
    ]
