# Generated by Django 2.1.7 on 2019-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0036_auto_20190523_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourregistration',
            name='verified_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
