# Generated by Django 2.1.7 on 2019-05-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0037_tourregistration_verified_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_regs', to='users.UserProfile'),
        ),
    ]
