# Generated by Django 2.1.7 on 2019-05-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0040_auto_20190523_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourregistration',
            old_name='tour_title',
            new_name='tour_group_title',
        ),
    ]
